import Link from "next/link";
import { ArrowRight, CalendarDays, MapPin, UsersRound } from "lucide-react";
import { currentMeeting } from "@/data/currentMeeting";

export default function MeetingPage() {
  return <main className="mx-auto max-w-6xl px-6 py-20 md:py-28"><p className="eyebrow">CURRENT MEETING</p>
    <div className="mt-5 grid gap-10 md:grid-cols-[1.15fr_.85fr] md:items-end"><div><h1 className="text-[42px] leading-[1.08] font-semibold tracking-[-0.04em] break-keep sm:text-5xl md:text-7xl">READ ME {currentMeeting.cohort}<br /><span className="text-[var(--forest)]">{currentMeeting.title}</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-[var(--muted)]">하나의 기수는 네 번의 모임으로 이어집니다. 참여자는 개별 회차가 아닌 전체 여정에 함께합니다.</p></div><div className="rounded-[28px] bg-[var(--forest)] p-7 text-[var(--cream)]"><p className="text-xs tracking-[.18em] text-[var(--sand)]">APPLICATION</p><p className="mt-3 text-2xl font-semibold">{currentMeeting.cohort} {currentMeeting.application.status}</p><p className="mt-3 text-sm leading-6 text-white/70">{currentMeeting.application.description}</p><Link href={currentMeeting.application.href} className="button button--light mt-6">{currentMeeting.application.actionLabel} <ArrowRight size={15}/></Link></div></div>
    <div className="mt-14 flex flex-wrap gap-3 text-sm text-[var(--muted)]"><span className="rounded-full border border-[var(--line)] px-4 py-2"><CalendarDays className="mr-2 inline" size={15}/>{currentMeeting.schedule}</span><span className="rounded-full border border-[var(--line)] px-4 py-2"><UsersRound className="mr-2 inline" size={15}/>{currentMeeting.capacity}</span><span className="rounded-full border border-[var(--line)] px-4 py-2"><MapPin className="mr-2 inline" size={15}/>{currentMeeting.location}</span></div>
    <section className="mt-16 border-t border-[var(--line)]">{currentMeeting.sessions.map((session) => <article key={session.order} className="grid gap-4 border-b border-[var(--line)] py-8 md:grid-cols-[100px_1fr_auto] md:items-center"><span className="text-sm font-semibold text-[var(--forest)]">{session.order}회차</span><div><h2 className="text-2xl font-semibold">{session.title}</h2><p className="mt-2 text-[var(--muted)]">{session.question}</p></div><span className="font-serif text-4xl text-[var(--sand)]">{String(session.order).padStart(2, "0")}</span></article>)}</section>
  </main>;
}
