create table if not exists public.interview_slots (
  id bigint generated by default as identity primary key,
  starts_at timestamptz not null unique,
  capacity smallint not null default 1 check (capacity between 1 and 20),
  is_open boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.interview_applications (
  id uuid primary key default gen_random_uuid(),
  slot_id bigint not null references public.interview_slots(id) on delete restrict,
  name text not null check (char_length(trim(name)) between 2 and 30),
  phone text not null check (phone ~ '^01(0|1|6|7|8|9)[0-9]{7,8}$'),
  status text not null default 'booked' check (status in ('booked', 'cancelled')),
  cancelled_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists interview_applications_active_phone_key
  on public.interview_applications (phone)
  where status = 'booked';

create index if not exists interview_applications_slot_status_idx
  on public.interview_applications (slot_id, status);

alter table public.interview_slots enable row level security;
alter table public.interview_applications enable row level security;

revoke all on table public.interview_slots from anon, authenticated;
revoke all on sequence public.interview_slots_id_seq from anon, authenticated;
revoke all on table public.interview_applications from anon, authenticated;

create or replace function public.list_available_interview_slots()
returns table (
  slot_id bigint,
  starts_at timestamptz
)
language sql
stable
security definer set search_path = ''
as $$
  select slot.id, slot.starts_at
  from public.interview_slots as slot
  where slot.is_open
    and slot.starts_at > now()
    and (
      select count(*)
      from public.interview_applications as application
      where application.slot_id = slot.id
        and application.status = 'booked'
    ) < slot.capacity
  order by slot.starts_at;
$$;

revoke all on function public.list_available_interview_slots() from public;
grant execute on function public.list_available_interview_slots() to anon, authenticated;

create or replace function public.submit_interview_application(
  p_slot_id bigint,
  p_name text,
  p_phone text
)
returns table (
  application_id uuid,
  starts_at timestamptz
)
language plpgsql
security definer set search_path = ''
as $$
declare
  selected_slot public.interview_slots%rowtype;
  normalized_phone text;
  booked_count integer;
  new_application_id uuid;
begin
  normalized_phone := regexp_replace(coalesce(p_phone, ''), '[^0-9]', '', 'g');

  if char_length(trim(coalesce(p_name, ''))) not between 2 and 30
    or normalized_phone !~ '^01(0|1|6|7|8|9)[0-9]{7,8}$' then
    raise exception 'invalid_application_content';
  end if;

  select candidate.*
  into selected_slot
  from public.interview_slots as candidate
  where candidate.id = p_slot_id
  for update;

  if not found
    or not selected_slot.is_open
    or selected_slot.starts_at <= now() then
    raise exception 'slot_unavailable';
  end if;

  select count(*)
  into booked_count
  from public.interview_applications as application
  where application.slot_id = selected_slot.id
    and application.status = 'booked';

  if booked_count >= selected_slot.capacity then
    raise exception 'slot_unavailable';
  end if;

  insert into public.interview_applications (slot_id, name, phone)
  values (selected_slot.id, trim(p_name), normalized_phone)
  returning id into new_application_id;

  return query select new_application_id, selected_slot.starts_at;
exception
  when unique_violation then
    raise exception 'already_applied';
end;
$$;

revoke all on function public.submit_interview_application(bigint, text, text) from public;
grant execute on function public.submit_interview_application(bigint, text, text) to anon, authenticated;

-- 운영 일정은 아래 형식으로 추가합니다.
-- insert into public.interview_slots (starts_at, capacity)
-- values ('2026-09-01 19:00:00+09', 1);
