create table if not exists public.session_answers (
  id bigint generated by default as identity primary key,
  cohort text not null references public.cohorts(name) on update cascade,
  week_number smallint not null check (week_number between 1 and 8),
  user_id uuid not null references auth.users(id) on delete cascade,
  display_name text not null check (char_length(display_name) between 2 and 30),
  content text not null check (char_length(trim(content)) between 2 and 2000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (cohort, week_number, user_id)
);

alter table public.session_answers enable row level security;

revoke all on table public.session_answers from anon;
grant select, insert, update on table public.session_answers to authenticated;

-- 정책 서브쿼리가 같은 테이블을 다시 조회할 때 RLS 재귀를 피하기 위한 security definer 함수
create or replace function public.has_answered(target_cohort text, target_week smallint)
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1 from public.session_answers
    where cohort = target_cohort
      and week_number = target_week
      and user_id = auth.uid()
  );
$$;

revoke all on function public.has_answered(text, smallint) from public;
grant execute on function public.has_answered(text, smallint) to authenticated;

-- 잠금 상태에서 흐림 처리된 말풍선 개수를 보여주기 위한 카운트 (내용은 노출하지 않음)
create or replace function public.session_answer_count(target_cohort text, target_week smallint)
returns integer
language sql
security definer
set search_path = public
stable
as $$
  select count(*)::int
  from public.session_answers
  where cohort = target_cohort
    and week_number = target_week;
$$;

revoke all on function public.session_answer_count(text, smallint) from public;
grant execute on function public.session_answer_count(text, smallint) to authenticated;

drop policy if exists "자신의 답변은 항상 조회 가능" on public.session_answers;
create policy "자신의 답변은 항상 조회 가능"
on public.session_answers for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "답변을 남긴 기수원만 같은 주차 답변 조회 가능" on public.session_answers;
create policy "답변을 남긴 기수원만 같은 주차 답변 조회 가능"
on public.session_answers for select
to authenticated
using (
  public.has_answered(cohort, week_number)
  and exists (
    select 1 from public.profiles p
    where p.id = (select auth.uid()) and p.cohort = session_answers.cohort
  )
);

drop policy if exists "자신의 기수에만 답변 작성 가능" on public.session_answers;
create policy "자신의 기수에만 답변 작성 가능"
on public.session_answers for insert
to authenticated
with check (
  (select auth.uid()) = user_id
  and exists (
    select 1 from public.profiles p
    where p.id = (select auth.uid()) and p.cohort = session_answers.cohort
  )
);

drop policy if exists "자신의 답변만 수정 가능" on public.session_answers;
create policy "자신의 답변만 수정 가능"
on public.session_answers for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);
