create table if not exists public.cohorts (
  name text primary key check (char_length(trim(name)) between 1 and 50),
  starts_at timestamptz not null,
  created_at timestamptz not null default now()
);

alter table public.cohorts enable row level security;
revoke all on table public.cohorts from anon, authenticated;
grant select on table public.cohorts to authenticated;

create table if not exists public.member_invitations (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) between 2 and 30),
  email text not null check (char_length(trim(email)) between 3 and 320),
  cohort text not null references public.cohorts(name) on update cascade,
  claimed_by uuid unique references auth.users(id) on delete set null,
  claimed_at timestamptz,
  created_at timestamptz not null default now()
);

create unique index if not exists member_invitations_normalized_email_key
  on public.member_invitations (lower(trim(email)));

alter table public.member_invitations enable row level security;
revoke all on table public.member_invitations from anon, authenticated;
revoke all on sequence public.member_invitations_id_seq from anon, authenticated;

alter table public.profiles
  add column if not exists full_name text,
  add column if not exists cohort text,
  add column if not exists cohort_message text not null default '',
  add column if not exists onboarding_completed_at timestamptz;

update public.profiles
set full_name = display_name
where full_name is null or trim(full_name) = '';

alter table public.profiles
  alter column full_name set not null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'profiles_cohort_fkey'
      and conrelid = 'public.profiles'::regclass
  ) then
    alter table public.profiles
      add constraint profiles_cohort_fkey
      foreign key (cohort) references public.cohorts(name) on update cascade;
  end if;
end;
$$;

drop policy if exists "회원은 자신의 기수 일정을 조회할 수 있음" on public.cohorts;
create policy "회원은 자신의 기수 일정을 조회할 수 있음"
on public.cohorts for select
to authenticated
using (
  exists (
    select 1
    from public.profiles as profile
    where profile.id = (select auth.uid())
      and profile.cohort = cohorts.name
  )
);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'profiles_full_name_length'
      and conrelid = 'public.profiles'::regclass
  ) then
    alter table public.profiles
      add constraint profiles_full_name_length
      check (char_length(trim(full_name)) between 2 and 30);
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'profiles_cohort_message_length'
      and conrelid = 'public.profiles'::regclass
  ) then
    alter table public.profiles
      add constraint profiles_cohort_message_length
      check (char_length(cohort_message) <= 300);
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'profiles_completed_onboarding_content'
      and conrelid = 'public.profiles'::regclass
  ) then
    alter table public.profiles
      add constraint profiles_completed_onboarding_content
      check (
        onboarding_completed_at is null
        or (
          char_length(trim(display_name)) between 2 and 30
          and char_length(trim(bio)) between 2 and 200
          and char_length(trim(cohort_message)) between 2 and 300
        )
      );
  end if;
end;
$$;

revoke update on table public.profiles from authenticated;
grant update (display_name, bio, cohort_message, updated_at) on table public.profiles to authenticated;

create or replace function public.is_member_invited(p_email text, p_name text)
returns boolean
language sql
stable
security definer set search_path = ''
as $$
  select exists (
    select 1
    from public.member_invitations as invitation
    where lower(trim(invitation.email)) = lower(trim(p_email))
      and trim(invitation.name) = trim(p_name)
      and invitation.claimed_at is null
      and invitation.claimed_by is null
  );
$$;

revoke all on function public.is_member_invited(text, text) from public, authenticated;
grant execute on function public.is_member_invited(text, text) to anon;

create or replace function public.complete_member_onboarding(
  p_display_name text,
  p_bio text,
  p_cohort_message text
)
returns void
language plpgsql
security definer set search_path = ''
as $$
begin
  if (select auth.uid()) is null then
    raise exception 'authentication_required';
  end if;

  if char_length(trim(p_display_name)) not between 2 and 30
    or char_length(trim(p_bio)) not between 2 and 200
    or char_length(trim(p_cohort_message)) not between 2 and 300 then
    raise exception 'invalid_onboarding_content';
  end if;

  update public.profiles
  set display_name = trim(p_display_name),
      bio = trim(p_bio),
      cohort_message = trim(p_cohort_message),
      onboarding_completed_at = now(),
      updated_at = now()
  where id = (select auth.uid())
    and onboarding_completed_at is null;

  if not found then
    raise exception 'onboarding_not_available';
  end if;
end;
$$;

revoke all on function public.complete_member_onboarding(text, text, text) from public, anon;
grant execute on function public.complete_member_onboarding(text, text, text) to authenticated;

create or replace function public.enforce_nickname_lock()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  if new.display_name is distinct from old.display_name
    and old.onboarding_completed_at is not null
    and exists (
      select 1
      from public.cohorts as cohort
      where cohort.name = old.cohort
        and cohort.starts_at <= now()
    ) then
    raise exception 'nickname_locked';
  end if;

  return new;
end;
$$;

drop trigger if exists enforce_profile_nickname_lock on public.profiles;
create trigger enforce_profile_nickname_lock
  before update of display_name on public.profiles
  for each row execute procedure public.enforce_nickname_lock();

revoke all on function public.enforce_nickname_lock() from public, anon, authenticated;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
declare
  invitation public.member_invitations%rowtype;
  signup_name text;
begin
  signup_name := trim(new.raw_user_meta_data ->> 'display_name');

  select candidate.*
  into invitation
  from public.member_invitations as candidate
  where lower(trim(candidate.email)) = lower(trim(new.email))
    and trim(candidate.name) = signup_name
    and candidate.claimed_at is null
    and candidate.claimed_by is null
  for update;

  if not found then
    raise exception 'signup_not_allowed';
  end if;

  insert into public.profiles (id, full_name, display_name, cohort)
  values (new.id, invitation.name, invitation.name, invitation.cohort)
  on conflict (id) do nothing;

  update public.member_invitations
  set claimed_by = new.id,
      claimed_at = now()
  where id = invitation.id;

  return new;
end;
$$;

revoke all on function public.handle_new_user() from public, anon, authenticated;
