create table if not exists public.membership_applications (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) between 2 and 30),
  email text not null check (char_length(trim(email)) between 3 and 320),
  cohort text not null references public.cohorts(name) on update cascade,
  message text not null default '' check (char_length(message) <= 1000),
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  admin_note text not null default '' check (char_length(admin_note) <= 1000),
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists membership_applications_pending_email_cohort_key
  on public.membership_applications (lower(trim(email)), cohort)
  where status = 'pending';

alter table public.membership_applications enable row level security;
revoke all on table public.membership_applications from anon, authenticated;
revoke all on sequence public.membership_applications_id_seq from anon, authenticated;

create or replace function public.submit_membership_application(
  p_name text,
  p_email text,
  p_cohort text,
  p_message text default ''
)
returns void
language plpgsql
security definer set search_path = ''
as $$
begin
  if char_length(trim(p_name)) not between 2 and 30
    or char_length(trim(p_email)) not between 3 and 320
    or char_length(coalesce(p_message, '')) > 1000 then
    raise exception 'invalid_application_content';
  end if;

  if not exists (
    select 1 from public.cohorts as cohort where cohort.name = trim(p_cohort)
  ) then
    raise exception 'invalid_cohort';
  end if;

  insert into public.membership_applications (name, email, cohort, message)
  values (trim(p_name), lower(trim(p_email)), trim(p_cohort), trim(coalesce(p_message, '')));
exception
  when unique_violation then
    null;
end;
$$;

revoke all on function public.submit_membership_application(text, text, text, text) from public;
grant execute on function public.submit_membership_application(text, text, text, text) to anon, authenticated;

create or replace function public.admin_list_membership_applications()
returns table (
  id bigint,
  name text,
  email text,
  cohort text,
  message text,
  status text,
  admin_note text,
  created_at timestamptz,
  reviewed_at timestamptz
)
language plpgsql
stable
security definer set search_path = ''
as $$
begin
  if coalesce((select auth.jwt() -> 'app_metadata' ->> 'role'), '') <> 'admin' then
    raise exception 'admin_required';
  end if;

  return query
  select
    application.id,
    application.name,
    application.email,
    application.cohort,
    application.message,
    application.status,
    application.admin_note,
    application.created_at,
    application.reviewed_at
  from public.membership_applications as application
  order by
    case application.status when 'pending' then 0 when 'approved' then 1 else 2 end,
    application.created_at desc;
end;
$$;

revoke all on function public.admin_list_membership_applications() from public, anon;
grant execute on function public.admin_list_membership_applications() to authenticated;

create or replace function public.review_membership_application(
  p_application_id bigint,
  p_decision text,
  p_admin_note text default ''
)
returns void
language plpgsql
security definer set search_path = ''
as $$
declare
  application public.membership_applications%rowtype;
  invitation public.member_invitations%rowtype;
begin
  if coalesce((select auth.jwt() -> 'app_metadata' ->> 'role'), '') <> 'admin' then
    raise exception 'admin_required';
  end if;

  if p_decision not in ('approved', 'rejected')
    or char_length(coalesce(p_admin_note, '')) > 1000 then
    raise exception 'invalid_review_content';
  end if;

  select candidate.*
  into application
  from public.membership_applications as candidate
  where candidate.id = p_application_id
  for update;

  if not found then
    raise exception 'application_not_found';
  end if;

  if application.status <> 'pending' then
    raise exception 'application_already_reviewed';
  end if;

  if p_decision = 'approved' then
    select candidate.*
    into invitation
    from public.member_invitations as candidate
    where lower(trim(candidate.email)) = lower(trim(application.email))
    for update;

    if found then
      if invitation.claimed_by is not null or invitation.claimed_at is not null then
        raise exception 'invitation_already_claimed';
      end if;

      update public.member_invitations
      set name = application.name,
          cohort = application.cohort
      where id = invitation.id;
    else
      insert into public.member_invitations (name, email, cohort)
      values (application.name, application.email, application.cohort);
    end if;
  end if;

  update public.membership_applications
  set status = p_decision,
      admin_note = trim(coalesce(p_admin_note, '')),
      reviewed_by = (select auth.uid()),
      reviewed_at = now(),
      updated_at = now()
  where id = application.id;
end;
$$;

revoke all on function public.review_membership_application(bigint, text, text) from public, anon;
grant execute on function public.review_membership_application(bigint, text, text) to authenticated;
